// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"go-buf-api-template/internal/conf"
	"go-buf-api-template/internal/platform/logger"
	"go-buf-api-template/internal/todo"
	"go-buf-api-template/internal/user"
)

// Injectors from wire.go:

// InitApp 构建应用：返回 App（Gin Engine + gRPC Server）与清理函数。
func InitApp(cfg *conf.Bootstrap) (*App, func(), error) {
	log := provideLogConfig(cfg)
	slogLogger := logger.New(log)
	database := provideDatabaseConfig(cfg)
	db, cleanup, err := provideDB(database, slogLogger)
	if err != nil {
		return nil, nil, err
	}
	service := todo.NewService(db, slogLogger)
	handler, err := todo.NewHandler(service, slogLogger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	server := todo.NewServer(service)
	userService := user.NewService(db, slogLogger)
	userHandler, err := user.NewHandler(userService, slogLogger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	userServer := user.NewServer(userService)
	grpcServer, err := provideGRPCServer(slogLogger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	app := NewApp(cfg, slogLogger, handler, server, userHandler, userServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
